# Generated by Django 3.1.7 on 2021-03-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=4)),
                ('passhash', models.CharField(max_length=64)),
            ],
        ),
    ]
