# Generated by Django 3.1.7 on 2021-03-29 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20210328_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('tokenID', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.user')),
            ],
        ),
    ]
