# Generated by Django 3.1.7 on 2021-03-29 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='User',
            new_name='userowo',
        ),
    ]
